version: '3.8'

services:
  db:
    image: postgres:12-alpine
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRESQL_NAME=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    env_file:
      - .env
    environment:
      - SECRET_KEY_BASE=V6aKNJydtn/VG/GHouW12CST2YOUEn9DjPUfs6r4kWrr9SUue+bpreN0UjEFPA9D
      - DATABASE_URL=ecto://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/app

volumes:
  postgres_data:
